using System;

namespace Inheritance
{
    // TODO: Declare "Book" as a subclass of Publication
    class Book : Publication
    {
        // Fields
        private string _author;

        // TODO: Using the base() keyword to initialize the base class
        public Book (string name, string author, int pagecount, decimal price)
        : base(name, pagecount, price)
        {
            _author = author;
        }

        // TODO: Using properties to set/get field shorthand what using the => operator
        public string Author 
        {
            get => _author;
            set => _author = value;
        }

        // TODO: Properties can be autogenerated to hold data
        public string ISBN { get; set; }

        // TODO: Use Override keyword to override a base class method
        public override string GetDescription()
        {
            return $"{Name} by {Author}, {PageCount} pages";
        }
    }
}